#!/bin/bash

make clean

rm ./config.h
rm ./config.log
rm ./config.status
rm ./config.cache
rm ./libtool
rm ./Makefile
rm ./stamp-h
rm ./stamp-h1

rm -r ./src/.deps
rm ./src/Makefile

rm ./src/moduls/Makefile

rm ./src/po/Makefile
rm ./src/po/*.po~

rm ./src/moduls/arhiv/Makefile
#Clean base
rm ./src/moduls/arhiv/base/Makefile
rm ./src/moduls/arhiv/base/po/Makefile
rm ./src/moduls/arhiv/base/po/*.po~
rm -r ./src/moduls/arhiv/base/.deps

rm ./src/moduls/bd/Makefile

rm ./src/moduls/ui/Makefile
#Clean web_cfg
rm ./src/moduls/ui/web_cfg/Makefile
rm ./src/moduls/ui/web_cfg/po/Makefile
rm ./src/moduls/ui/web_cfg/po/*.po~
rm -r ./src/moduls/ui/web_cfg/.deps

rm ./src/moduls/protocol/Makefile
#Clean http
rm ./src/moduls/protocol/http/Makefile
rm ./src/moduls/protocol/http/po/Makefile
rm ./src/moduls/protocol/http/po/*.po~
rm -r ./src/moduls/protocol/http/.deps

rm ./src/moduls/special/Makefile

rm ./src/moduls/tcontr/Makefile
#Clean virtual_v1
rm ./src/moduls/tcontr/virtual1/Makefile
rm ./src/moduls/tcontr/virtual1/po/Makefile
rm ./src/moduls/tcontr/virtual1/po/*.po~
rm -r ./src/moduls/tcontr/virtual1/.deps

rm ./src/moduls/transport/Makefile
#Clean socket
rm ./src/moduls/transport/socket/Makefile
rm ./src/moduls/transport/socket/po/Makefile
rm ./src/moduls/transport/socket/po/*.po~
rm -r ./src/moduls/transport/socket/.deps


