#!/bin/sh

# Use for core dump creation on programm crash
ulimit -c unlimited

# Programm command and lock file
pCmd="./openscada --Config=$(pwd)/../etc/oscada_demo.xml"
pLock=".demo.lock"

# Check for already started programm present
if [ -f $pLock ] && ps -Ao pid,command | grep "$(cat ${pLock})[ ]*${pCmd}" > /dev/null; then
    echo "OpenSCADA demo-station already started!";
    exit 1;
fi

# Call programm
$pCmd $@ &
pPid=$!

# Create lock file
echo $pPid > $pLock

# Wait for programm stop
wait $pPid
echo "Program rezult: $?"

# Remove lock file
rm -f $pLock
