#!/bin/sh

# Programm command and lock file
pCmd="./openscada --CoreDumpAllow --Config=$(pwd)/../etc/oscada_demo.xml"
pLock=".demo.lock"

# Check for already started programm present
if [ -f $pLock ] && ps -Ao pid,command | grep "$(cat ${pLock})[ ]*${pCmd}" > /dev/null; then
    echo "OpenSCADA demo-station already started!";
    exit 1;
fi

# Call programm
$pCmd $@ &
pPid=$!

# Create lock file
echo $pPid > $pLock

# Wait for programm stop
wait $pPid
echo "Program rezult: $?"

# Core dump file "core" into work directory process
if [ -f ../share/openscada/core -a -n "$(which gdb)" ]; then
    pCmd="$(pwd)/openscada"
    cd ../share/openscada/
    echo "Core dump process for back trace purchase to file crash_$(date +%F_%H:%M).txt"
    gdb $pCmd --core core --batch --quiet -ex "thread apply all bt full" -ex "quit" > crash_$(date +%F_%H:%M).txt
    rm -f core
fi

# Remove lock file
rm -f $pLock
