#!/bin/bash

# Use for core dump creation on programm crash
ulimit -c unlimited

# User directory prepare
if [ ! -d ~/.openscada ]; then install -m 755 -d ~/.openscada; fi
if [ ! -d ~/.openscada/ARCHIVES ]; then install -m 755 -d ~/.openscada/ARCHIVES/{MESS,VAL}; fi
if [ ! -L ~/.openscada/icons ]; then ln -s /var/spool/openscada/icons ~/.openscada/icons; fi
if [ ! -d ~/.openscada/DEMO ]; then cp -R /var/spool/openscada/DEMO ~/.openscada/; fi
if [ ! -e ~/.openscada/oscada_demo.xml ]; then install -m 644 /etc/oscada_demo.xml ~/.openscada/; fi
cd ~/.openscada

# Programm command and lock file
pCmd="openscada --Config=./oscada_demo.xml"
pLock=".demo.lock"

# Check for already started programm present
if [ -f $pLock ] && ps -Ao pid,command | grep "$(cat ${pLock})[ ]*${pCmd}" > /dev/null; then
    echo "OpenSCADA demo-station already started!";
    exit 1;
fi

# Call programm
$pCmd $@ &
pPid=$!

# Create lock file
echo $pPid > $pLock

# Wait for programm stop
wait $pPid
echo "Programm result: $?"

# Remove lock file
rm -f $pLock
