## Process this file with automake to produce Makefile.in

pkglib_LTLIBRARIES = test_bd.la
pkglib_LTLIBRARIES = test_bd1.la

test_bd_la_SOURCES = test_bd.cpp 
test_bd_la_LDFLAGS = -export-dynamic -module -avoid-version

test_bd1_la_SOURCES = test_bd1.cpp 
test_bd1_la_LDFLAGS = -export-dynamic -module -avoid-version

#INCLUDES = -I$(top_srcdir)/intl -I$(srcdir)/../../lib $(GTK_CFLAGS) $(GNOME_CFLAGS) $(FREETYPE_CFLAGS) $(XML_CFLAGS) $(UNICODE_CFLAGS) $(DEBUG_FLAGS)
